//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumProfilesEveryRunning {
            get {
                return ((int)(this["NumProfilesEveryRunning"]));
            }
            set {
                this["NumProfilesEveryRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfiles {
            get {
                return ((int)(this["TotalProfiles"]));
            }
            set {
                this["TotalProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRunProfilesInstalled {
            get {
                return ((bool)(this["IsRunProfilesInstalled"]));
            }
            set {
                this["IsRunProfilesInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoRunServices {
            get {
                return ((bool)(this["IsAutoRunServices"]));
            }
            set {
                this["IsAutoRunServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("paidviewpoint.com/?r=ar7yg9")]
        public string Link_Paidviewpoint {
            get {
                return ((string)(this["Link_Paidviewpoint"]));
            }
            set {
                this["Link_Paidviewpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("indexbitco.in/index&ref=17409")]
        public string Link_Indexbitco {
            get {
                return ((string)(this["Link_Indexbitco"]));
            }
            set {
                this["Link_Indexbitco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("presearch.org/signup?rid=227755")]
        public string Link_Presearch {
            get {
                return ((string)(this["Link_Presearch"]));
            }
            set {
                this["Link_Presearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("timebucks.com/?refID=215091225")]
        public string Link_Timebucks {
            get {
                return ((string)(this["Link_Timebucks"]));
            }
            set {
                this["Link_Timebucks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesTimebucks {
            get {
                return ((int)(this["TotalProfilesTimebucks"]));
            }
            set {
                this["TotalProfilesTimebucks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTimebucksTask {
            get {
                return ((bool)(this["isTimebucksTask"]));
            }
            set {
                this["isTimebucksTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPresearchTask {
            get {
                return ((bool)(this["isPresearchTask"]));
            }
            set {
                this["isPresearchTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumOfProfilesInstalled {
            get {
                return ((int)(this["NumOfProfilesInstalled"]));
            }
            set {
                this["NumOfProfilesInstalled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoProcesses {
            get {
                return ((string)(this["AutoProcesses"]));
            }
            set {
                this["AutoProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CreateProfilesProcesses {
            get {
                return ((string)(this["CreateProfilesProcesses"]));
            }
            set {
                this["CreateProfilesProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CreateAccountsProcesses {
            get {
                return ((string)(this["CreateAccountsProcesses"]));
            }
            set {
                this["CreateAccountsProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesPresearch {
            get {
                return ((int)(this["TotalProfilesPresearch"]));
            }
            set {
                this["TotalProfilesPresearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesPaidviewpoint {
            get {
                return ((int)(this["TotalProfilesPaidviewpoint"]));
            }
            set {
                this["TotalProfilesPaidviewpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPaidviewpointTask {
            get {
                return ((bool)(this["isPaidviewpointTask"]));
            }
            set {
                this["isPaidviewpointTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isIndexbitcoTask {
            get {
                return ((bool)(this["isIndexbitcoTask"]));
            }
            set {
                this["isIndexbitcoTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isFreebitcoinTask {
            get {
                return ((bool)(this["isFreebitcoinTask"]));
            }
            set {
                this["isFreebitcoinTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoFreebitcoTask {
            get {
                return ((bool)(this["isAutoFreebitcoTask"]));
            }
            set {
                this["isAutoFreebitcoTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesIndexbitco {
            get {
                return ((int)(this["TotalProfilesIndexbitco"]));
            }
            set {
                this["TotalProfilesIndexbitco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesFreebitcoin {
            get {
                return ((int)(this["TotalProfilesFreebitcoin"]));
            }
            set {
                this["TotalProfilesFreebitcoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesAdbtc {
            get {
                return ((int)(this["TotalProfilesAdbtc"]));
            }
            set {
                this["TotalProfilesAdbtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("freebitcoin.io/?ref=143051")]
        public string Link_Freebitcoin {
            get {
                return ((string)(this["Link_Freebitcoin"]));
            }
            set {
                this["Link_Freebitcoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Link_Adbtc {
            get {
                return ((string)(this["Link_Adbtc"]));
            }
            set {
                this["Link_Adbtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesAuto {
            get {
                return ((int)(this["TotalProfilesAuto"]));
            }
            set {
                this["TotalProfilesAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesAutoProxy {
            get {
                return ((int)(this["TotalProfilesAutoProxy"]));
            }
            set {
                this["TotalProfilesAutoProxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesManual {
            get {
                return ((int)(this["TotalProfilesManual"]));
            }
            set {
                this["TotalProfilesManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalProfilesManualProxy {
            get {
                return ((int)(this["TotalProfilesManualProxy"]));
            }
            set {
                this["TotalProfilesManualProxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManualProcesses {
            get {
                return ((string)(this["ManualProcesses"]));
            }
            set {
                this["ManualProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FromProfile {
            get {
                return ((int)(this["FromProfile"]));
            }
            set {
                this["FromProfile"] = value;
            }
        }
    }
}
